Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	2	IDtaxa
	1	all
	1	build_tree
	1	combine_read_counts
	1	get_rep_seq
	6

[Thu Nov 29 11:53:53 2018]
rule combine_read_counts:
    input: stats/Nreads_filtered.txt, stats/Nreads_dereplicated.txt, stats/Nreads_chimera_removed.txt
    output: stats/Nreads.tsv, stats/Nreads.pdf
    jobid: 5

Removing temporary output file stats/Nreads_chimera_removed.txt.
Removing temporary output file stats/Nreads_dereplicated.txt.
[Thu Nov 29 11:53:55 2018]
Finished job 5.
1 of 6 steps (17%) done

[Thu Nov 29 11:53:55 2018]
rule IDtaxa:
    input: output/seqtab.rds, /Users/silas/Desktop/WarmMicrobiota/TaxonmyDBs/SILVA_SSU_r132_March2018.RData
    output: taxonomy/Silva.tsv
    log: logs/dada2/IDtaxa_Silva.txt
    jobid: 1
    wildcards: ref=Silva

[Thu Nov 29 11:54:24 2018]
Error in rule IDtaxa:
    jobid: 1
    output: taxonomy/Silva.tsv
    log: logs/dada2/IDtaxa_Silva.txt

RuleException:
CalledProcessError in line 109 of /Users/silas/Documents/GitHub/amplicon-seq-dada2/rules/dada2.smk:
Command ' set -euo pipefail;  Rscript /Users/silas/Desktop/WarmMicrobiota/Sequencing_C/Analysis/.snakemake/scripts/tmpw0q8vwd9.IDtaxa.R ' returned non-zero exit status 1.
  File "/Users/silas/Documents/GitHub/amplicon-seq-dada2/rules/dada2.smk", line 109, in __rule_IDtaxa
  File "/Users/silas/anaconda3/lib/python3.6/concurrent/futures/thread.py", line 55, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /Users/silas/Desktop/WarmMicrobiota/Sequencing_C/Analysis/.snakemake/log/2018-11-29T115353.385336.snakemake.log
