Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	2	IDtaxa
	1	all
	1	build_tree
	1	filterLength
	1	get_rep_seq
	6

[Thu Nov 29 14:57:00 2018]
rule filterLength:
    input: output/seqtab_nochimeras.rds
    output: figures/Lengths/Sequence_Length_distribution.pdf, figures/Lengths/Sequence_Length_distribution_abundance.pdf, output/seqtab.rds, output/seqtab.tsv
    log: logs/dada2/filterLength.txt
    jobid: 1

[Thu Nov 29 14:57:10 2018]
Finished job 1.
1 of 6 steps (17%) done

[Thu Nov 29 14:57:10 2018]
rule IDtaxa:
    input: output/seqtab.rds, /Users/silas/Desktop/WarmMicrobiota/TaxonmyDBs/SILVA_SSU_r132_March2018.RData
    output: taxonomy/Silva.tsv
    log: logs/dada2/IDtaxa_Silva.txt
    jobid: 4
    wildcards: ref=Silva

[Thu Nov 29 14:57:18 2018]
Error in rule IDtaxa:
    jobid: 4
    output: taxonomy/Silva.tsv
    log: logs/dada2/IDtaxa_Silva.txt

RuleException:
CalledProcessError in line 109 of /Users/silas/Documents/GitHub/amplicon-seq-dada2/rules/dada2.smk:
Command ' set -euo pipefail;  Rscript /Users/silas/Desktop/WarmMicrobiota/Sequencing_C/Analysis/.snakemake/scripts/tmp7o12l4u5.IDtaxa.R ' returned non-zero exit status 1.
  File "/Users/silas/Documents/GitHub/amplicon-seq-dada2/rules/dada2.smk", line 109, in __rule_IDtaxa
  File "/Users/silas/anaconda3/lib/python3.6/concurrent/futures/thread.py", line 55, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /Users/silas/Desktop/WarmMicrobiota/Sequencing_C/Analysis/.snakemake/log/2018-11-29T145659.450036.snakemake.log
